name: notify-status sample pipeline

on:
  push:
    branches: [main]

jobs:
  notify-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run a step
        run: echo "Run step"

      - name: Send slack notification
        uses: marcdomain/notify-status@v1
        if: always()
        with:
          app: Slack
          status: ${{ job.status }}
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          message: Notification sent successfully
